package component:root;

world imports {
    include wasi:io/imports@0.2.9;
    include wasi:random/imports@0.2.9;
    include wasi:clocks/imports@0.2.9;
    include wasi:sockets/imports@0.2.9;
    include wasi:filesystem/imports@0.2.9;
    include wasi:cli/imports@0.2.9;
    include wasi:http/imports@0.2.9;
}
