//go:build wasip2

// Code generated by wit-bindgen-go. DO NOT EDIT.

package stdin

// This file contains wasmimport and wasmexport declarations for "wasi:cli@0.2.9".

//go:wasmimport wasi:cli/stdin@0.2.9 get-stdin
//go:noescape
func wasmimport_GetStdin() (result0 uint32)
