//go:build wasip2

// Code generated by wit-bindgen-go. DO NOT EDIT.

package instancenetwork

// This file contains wasmimport and wasmexport declarations for "wasi:sockets@0.2.9".

//go:wasmimport wasi:sockets/instance-network@0.2.9 instance-network
//go:noescape
func wasmimport_InstanceNetwork() (result0 uint32)
