//go:build wasip2

// Code generated by wit-bindgen-go. DO NOT EDIT.

package network

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasi:sockets@0.2.9".

//go:wasmimport wasi:sockets/network@0.2.9 [resource-drop]network
//go:noescape
func wasmimport_NetworkResourceDrop(self0 uint32)

//go:wasmimport wasi:sockets/network@0.2.9 network-error-code
//go:noescape
func wasmimport_NetworkErrorCode(err0 uint32, result *cm.Option[ErrorCode])
