//go:build wasip2

// Code generated by wit-bindgen-go. DO NOT EDIT.

package timezone

// This file contains wasmimport and wasmexport declarations for "wasi:clocks@0.2.9".

//go:wasmimport wasi:clocks/timezone@0.2.9 display
//go:noescape
func wasmimport_Display(when0 uint64, when1 uint32, result *TimezoneDisplay)

//go:wasmimport wasi:clocks/timezone@0.2.9 utc-offset
//go:noescape
func wasmimport_UtcOffset(when0 uint64, when1 uint32) (result0 uint32)
